project_id = "ywohajmeijjiubesykcu"

[functions.save-to-ledger]
verify_jwt = false

[functions.chat-openai]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.chat-claude]
verify_jwt = false

[functions.chat-deepseek]
verify_jwt = false

[functions.check-subscription]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true